#!/usr/bin/env python3
"""Перенести снимок открытого журнала решений в платформу.

Простыми словами: платформа (papka platform/) собирается отдельно и не должна
во время работы ходить на чужие серверы (требование прозрачности — ничего не
подгружается со стороны). Поэтому мы заранее кладём рядом с платформой снимок
открытого журнала решений из governance/registry/index.json. Экран «Открытый
журнал» читает этот снимок и показывает его людям.

Снимок намеренно делается обычным файлом данных (platform/lib/journal-data.json):
позже, когда контракты запустят в тестовой сети, тот же экран можно будет
переключить на чтение «вживую» из реестра или из блокчейна — без переписывания
интерфейса (слой данных отделён от экрана).

Запуск из корня репозитория:  python3 scripts/sync_journal.py
Проверка без записи:          python3 scripts/sync_journal.py --check

Зависимостей нет — только стандартная библиотека Python.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "governance" / "registry" / "index.json"
TARGET = ROOT / "platform" / "lib" / "journal-data.json"

# Поля, которые экрану действительно нужны (всё это уже публично в реестре).
ENTRY_FIELDS = ("seq", "id", "type", "timestamp", "summary", "hash", "file")


def build_snapshot() -> dict:
    index = json.loads(SOURCE.read_text(encoding="utf-8"))
    entries = []
    for raw in index.get("entries", []):
        entries.append({k: raw.get(k) for k in ENTRY_FIELDS})
    return {
        "note": (
            "Снимок открытого журнала решений из governance/registry/index.json. "
            "Сгенерирован scripts/sync_journal.py. Не редактировать вручную. / "
            "Snapshot of the open decision record from "
            "governance/registry/index.json. Generated by scripts/sync_journal.py. "
            "Do not edit by hand."
        ),
        "count": index.get("count"),
        "headHash": index.get("head_hash"),
        "entries": entries,
    }


def render(snapshot: dict) -> str:
    # Стабильный, читаемый JSON: один и тот же ввод даёт один и тот же файл
    # (важно для детерминизма и чистого git-diff).
    return json.dumps(snapshot, ensure_ascii=False, indent=2, sort_keys=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Снимок журнала решений для платформы")
    parser.add_argument(
        "--check",
        action="store_true",
        help="только проверить, что снимок свежий (ничего не записывать)",
    )
    args = parser.parse_args()

    if not SOURCE.exists():
        print(f"НЕТ ИСТОЧНИКА: {SOURCE}", file=sys.stderr)
        return 2

    snapshot = build_snapshot()
    rendered = render(snapshot)

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(
                "Снимок журнала устарел — запустите: python3 scripts/sync_journal.py",
                file=sys.stderr,
            )
            return 1
        print(f"Снимок журнала свежий: {snapshot['count']} записей.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Снимок журнала обновлён: {snapshot['count']} записей → {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
